Refactor: Migrate from nfsroot to iscsi blockdevice
This is the largest change in lapas since .. lapas.
The decision for this was driven by multiple things:
 - umu-launcher (unnecessarily) uses complex atomic fs-syscalls not supported by nfs
   This makes the launcher's upstream version stop working on lapas - even though the actually complicated
   part (wine/proton) would work flawlessly in this environment
 - nfs clients can not be persuaded to infinitely cache read data/metadata
   This makes total sense - of course - but is very bad for goldsource based games, which (unnecessarily) perform a million file
   stats on startup of the same files, again and again - with nfs not allowed to cache the result
 - Largest disadvantage of nfs is that nfsroot support is not built into any standard distribution kernel
   This is why we build our own kernel. Many standard distribution kernels support iscsi as module though.
   By simply adding the iscsi_tcp module to the initramfs, we could use these pre-built kernels.
   The strong disadvantage of this being, that it might open the door for proper secureboot support!

diff --git a/res/lapas/guest/etc/initcpio/install/lapas b/res/lapas/guest/etc/initcpio/install/lapas
--- a/res/lapas/guest/etc/initcpio/install/lapas
+++ b/res/lapas/guest/etc/initcpio/install/lapas
@@ -1,26 +1,28 @@
 #!/bin/bash
 
 build() {
-	# Add firmware files for network card drivers that are built directly into the kernel
-	local mods firmware;
-	mapfile -t mods < <(cat "/usr/lib/modules/${KERNELVERSION}/modules.builtin" | grep "/drivers/net");
+        # Add firmware files for network card drivers that are built directly into the kernel
+        local mods firmware;
+        mapfile -t mods < <(cat "/usr/lib/modules/${KERNELVERSION}/modules.builtin" | grep "/drivers/net");
 
-	for modPath in "${mods[@]}"; do
-		modFilename=$(basename "$modPath");
-		modName=${modFilename%.ko*};
-		mapfile -t firmware < <(modinfo -k "$KERNELVERSION" "$modName" | grep -E "^firmware:\s+" | awk '{ print $2 }');
-		if (( ${#firmware[*]} )); then
-			echo -e "\tAdding ${#firmware[@]} firmware files for: $modName";
-			add_firmware "${firmware[@]}" || { echo -e "\t\tWarning: Firmware may be missing"; };
-		fi
-	done
+        for modPath in "${mods[@]}"; do
+                modFilename=$(basename "$modPath");
+                modName=${modFilename%.ko*};
+                mapfile -t firmware < <(modinfo -k "$KERNELVERSION" "$modName" | grep -E "^firmware:\s+" | awk '{ print $2 }');
+                if (( ${#firmware[*]} )); then
+                        echo -e "\tAdding ${#firmware[@]} firmware files for: $modName";
+                        add_firmware "${firmware[@]}" || { echo -e "\t\tWarning: Firmware may be missing"; };
+                fi
+        done
 
-	# Add all network card drivers built as modules and their corresponding firmware files
-	add_all_modules '/drivers/net/'
+        # Add all network card drivers built as modules and their corresponding firmware files
+        add_all_modules '/drivers/net/'
 
-	add_binary "/usr/bin/mount.nfs4" "/bin/mount.nfs4"
+        add_binary tr;
+        add_binary blockdev;
+        add_binary iscsistart;
 
-	add_runscript
+        add_runscript
 }
 
 help() {
@@ -28,3 +30,4 @@ help() {
 This installs our remountfs script.
 HELPEOF
 }
+
